name: UMLet-MCM

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install devbox  
      uses: jetify-com/devbox-install-action@v0.11.0
    - name: Install packages
      run: devbox install
    - name: Test 
      run: devbox run -- make test
    - name: Build 
      run: devbox run -- make
    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Push
      run: devbox run -- make push
       
